version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=acornserver
    volumes:
      - postgres-data:/var/lib/postgresql/data # default postgres directory
    profiles: ["production", "development"]

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - pgadmin-data:/var/lib/pgadmin # default pgadmin directory
    depends_on:
      - postgres
    profiles: ["production", "development"]

  acornserver:
    image: acornserver
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=acornserver
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - acorn-data:/usr/src/acornserver/media # directory for user-uploaded files
    depends_on:
      - postgres
    profiles: ["production"]

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  acorn-data:
    driver: local
